variables:
  PYTORCH_IMAGE: registry.sensetime.com/openmmlab/pytorch18-cu102-mmcv-transforms:update-repo

stages:
  # - linting
  - test
  - deploy

before_script:
  - . /root/scripts/set_envs.sh
  - echo $PATH
  - gcc --version
  - nvcc --version
  - ruby --version
  - python --version
  - pip --version
  - python -c "import torch; print(torch.__version__)"
  - python -c "import mmcv; print(mmcv.__version__)"

linting:
  image: $PYTORCH_IMAGE
  stage: test
  script:
    - pre-commit run --all-files

.test_template: &test_template_def
  stage: test
  script:
    - echo "Configurating git..."
    - git config --local core.sshCommand "/usr/bin/ssh -i /root/.ssh/id_gitlab"
    - echo "Installing mmdet..."
    - git clone --branch master -c core.sshCommand="/usr/bin/ssh -i /root/.ssh/id_gitlab" git@gitlab.sh.sensetime.com:openmmlab-enterprise/openmmlab-ce/mmdetection.git /mmdet
    - http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= pip install -e /mmdet -i https://pypi.tuna.tsinghua.edu.cn/simple/
    - python -c "import mmdet; print(mmdet.__version__)"
    - echo "Installing mmseg..."
    - git clone --branch master -c core.sshCommand="/usr/bin/ssh -i /root/.ssh/id_gitlab" git@gitlab.sh.sensetime.com:openmmlab-enterprise/openmmlab-ce/mmsegmentation.git /mmseg
    - http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= pip install -e /mmseg -i https://pypi.tuna.tsinghua.edu.cn/simple/
    - python -c "import mmseg; print(mmseg.__version__)"
    - echo "Start building..."
    - http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= pip install -e .[all] -i https://pypi.tuna.tsinghua.edu.cn/simple/
    - echo "Start testing..."
    - python -c "import mmdet3d; print(mmdet3d.__version__)"
    - coverage run --branch --source mmdet3d -m pytest tests/
    # Test if python files being added or modified meet our unittest and docstring coverage requirements
    - REUSE_COVERAGE_REPORT=1 .dev_scripts/diff_coverage_test.sh
    # Report global unittest and docstring coverages
    - coverage report -m
    - interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-magic --ignore-regex "__repr__" --fail-under 60 mmdet3d

test:pytorch1.8-cuda10:
  image: $PYTORCH_IMAGE
  <<: *test_template_def
